#include "rooms/room_bananadroparea.cpp"
#include "rooms/room_cathedral.cpp"
#include "rooms/room_library.cpp"
#include "rooms/room_normalroom.cpp"
#include "rooms/room_shop.cpp"
#include "rooms/room_sumoarena.cpp"
#include "rooms/room_vault.cpp"
