#include "room_normalroom.cpp"
#include "room_shop.cpp"
#include "room_cathedral.cpp"
#include "room_library.cpp"
#include "room_bananadroparea.cpp"
#include "room_sumoarena.cpp"
#include "room_vault.cpp"
