IVAN_DATA_DIR ?= share/ivan ;

InstallBin bin : ivan ;

ivan-data-dirs =
  Graphics
  Sound
  Script
  Script/chars
  Script/dungeons
  Script/glterras
  Script/items
  Script/materials
  Script/olterras
  Script/zext
  Script/zext/k8
  Script/zext/k8/chars
  Script/zext/k8/chars
;

for idd in $(ivan-data-dirs) {
  InstallFile $(IVAN_DATA_DIR)/$(idd) : [ Glob $(TOP)/$(idd) : "*" : files-only full-path ] ;
}
