/* DO NOT CHANGE THE ORDER! */
#include "valpurus.cpp"
#include "legifer.cpp"
#include "atavus.cpp"
#include "dulcis.cpp"
#include "seges.cpp"
#include "sophos.cpp"
#include "silva.cpp"
#include "loricatus.cpp"
#include "mellis.cpp"
#include "cleptia.cpp"
#include "nefas.cpp"
#include "scabies.cpp"
#include "infuscor.cpp"
#include "cruentus.cpp"
#include "mortifer.cpp"
