/* DO NOT CHANGE THE ORDER! */
#include "god_valpurus.cpp"
#include "god_legifer.cpp"
#include "god_atavus.cpp"
#include "god_dulcis.cpp"
#include "god_seges.cpp"
#include "god_sophos.cpp"
#include "god_silva.cpp"
#include "god_loricatus.cpp"
#include "god_mellis.cpp"
#include "god_cleptia.cpp"
#include "god_nefas.cpp"
#include "god_scabies.cpp"
#include "god_infuscor.cpp"
#include "god_cruentus.cpp"
#include "god_mortifer.cpp"
