#include "humans/character_humanoid.cpp"

#include "humans/humanoid_playerkind.cpp"
#include "humans/playerkind_slave.cpp"

#include "humans/humanoid_priest.cpp"
#include "humans/priest_exiledpriest.cpp"

#include "humans/humanoid_angel.cpp"
#include "humans/angel_archangel.cpp"
#include "humans/angel_insudo.cpp"

#include "humans/humanoid_kamikazedwarf.cpp"
#include "humans/kamikazedwarf_rookiekamikazedwarf.cpp"
#include "humans/kamikazedwarf_veterankamikazedwarf.cpp"
#include "humans/kamikazedwarf_grenadierdwarf.cpp"

#include "humans/humanoid_axethrowerdwarf.cpp"

#include "humans/humanoid_genie.cpp"
#include "humans/genie_reaper.cpp"

#include "humans/humanoid_petrusswife.cpp"
#include "humans/humanoid_petrus.cpp"
#include "humans/humanoid_farmer.cpp"
#include "humans/humanoid_guard.cpp"
#include "humans/humanoid_shopkeeper.cpp"
#include "humans/humanoid_oree.cpp"
#include "humans/humanoid_darkknight.cpp"
#include "humans/humanoid_ennerbeast.cpp"
#include "humans/humanoid_skeleton.cpp"
#include "humans/humanoid_goblin.cpp"
#include "humans/humanoid_golem.cpp"
#include "humans/humanoid_communist.cpp"
#include "humans/humanoid_hunter.cpp"
#include "humans/humanoid_housewife.cpp"
#include "humans/humanoid_femaleslave.cpp"
#include "humans/humanoid_librarian.cpp"
#include "humans/humanoid_zombie.cpp"
#include "humans/humanoid_imp.cpp"
#include "humans/humanoid_mistress.cpp"
#include "humans/humanoid_werewolfhuman.cpp"
#include "humans/humanoid_werewolfwolf.cpp"
#include "humans/humanoid_kobold.cpp"
#include "humans/humanoid_gibberling.cpp"
#include "humans/humanoid_orc.cpp"
#include "humans/humanoid_cossack.cpp"
#include "humans/humanoid_bananagrower.cpp"
#include "humans/humanoid_mangogrower.cpp"
#include "humans/humanoid_imperialist.cpp"
#include "humans/humanoid_smith.cpp"
#include "humans/humanoid_elder.cpp"
#include "humans/humanoid_encourager.cpp"
#include "humans/humanoid_darkmage.cpp"
#include "humans/humanoid_necromancer.cpp"
#include "humans/humanoid_sumowrestler.cpp"
#include "humans/humanoid_tourist.cpp"
#include "humans/humanoid_tailor.cpp"
#include "humans/humanoid_siren.cpp"
#include "humans/humanoid_punisher.cpp"
#include "humans/humanoid_mysteryman.cpp"
#include "humans/humanoid_denim.cpp"
#include "humans/humanoid_raven.cpp"
#include "humans/humanoid_wisefarmer.cpp"
#include "humans/humanoid_vulcan.cpp"
#include "humans/humanoid_bum.cpp"
#include "humans/humanoid_rogue.cpp"
#include "humans/humanoid_assassin.cpp"
#include "humans/humanoid_shaman.cpp"
#include "humans/humanoid_warlock.cpp"
#include "humans/humanoid_alchemist.cpp"
#include "humans/humanoid_doctor.cpp"
#include "humans/humanoid_vampire.cpp"
