#include "gwterrain_ocean.cpp"
#include "gwterrain_glacier.cpp"
#include "gwterrain_desert.cpp"
#include "gwterrain_snow.cpp"
#include "gwterrain_jungle.cpp"
#include "gwterrain_leafyforest.cpp"
#include "gwterrain_evergreenforest.cpp"
#include "gwterrain_steppe.cpp"
